name: PHP Copy/Paste Detector

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the docker image
        run: make build-dev
      - name: Start the docker image
        run: make start
      - name: Check running container
        run: docker ps -a
      - name: Show php, composer, phing, phive versions
        run: make info
      - name: Cleanup build artifacts and install dependencies with composer
        run: make setup
      - name: Run test suite
        run: make phpunit
      - name: Stop and remove environment container, network
        run: make down
